name: 06 - Contexts 

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Context Information
        run: |
           echo 'Event name : ${{ github.event_name }}'