name: 02 - Workflow Events

on:
  workflow_dispatch:

jobs:
    Test:
        runs-on: ubuntu-latest

        steps:
            - name: Log the event triggered
              run: echo "I have been trigger by and ${{ github.event_name}}"
            
            - name: Checkout the repository
              run: echo "Checking out the repository"