name: Git Action

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: 01-using-action/my-react
        steps:
            - name: checkout repository
              uses: actions/checkout@v4
            
            - name: list the folder structure
              run: |
                ls
            
            - name: install the node
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
              
            - name: install the dependencies
              run: npm ci
            
            - name: run the unit test
              run: npm run test
