name: 06 - Contexts 

run-name: My custom workflow run name - ${{ inputs.debug }} 

on:
  push:
  workflow_dispatch:
    inputs:
      debug: 
        description: 'Tag is used to display the custom run name'
        type: boolean
        default: false

env:
  TOP_TOKEN: ${{ vars.MY_VAR }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Context Information
        run: |
           echo 'Event name : ${{ github.event_name }}'
           echo 'Refs name : $${{ github.ref}}'
           echo 'Repository name : ${{ github.repository }}'
           echo 'Actor : ${{ github.actor }}'
           echo 'Workflow : ${{ github.workflow }}'
    
      - name: Retrieve Variable
        run: |
           echo "Retriving the Variable ${{ vars.MY_VAR}}"
      
      - name: Retrive the ENV details 
        run: |
            echo "Retive the Env Details ${{ env.TOP_TOKEN }}"
      