name: 17 - 2 - JS Custom Actions
run-name: 17 - 2 - JS Custom Actions - JS | env ${{ inputs.target-env }}

on:
    workflow_dispatch:
      
jobs:
    depedency-update:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4

            - name: check for depedency updates
              uses: ./.github/workflows/actions/js-depedence-update


            - name: set up node dependencies
              uses: ./.github/workflows/actions/composite-cache-deps
              with:
                node-version: 20.x
                working-dir: ${{ env.working-directory }}
                target-env: ${{ inputs.target-env}}
           
            - name: Test
              run: npm run test
            

            - name: Build
              run: npm run build
            