name: 17 - 2 - JS Custom Actions
run-name: 17 - 2 - JS Custom Actions - JS | BB ${{ inputs.base-branch}} - TB ${{ inputs.target-branch}}  - WD ${{ inputs.working-dir}}

on:
    workflow_dispatch:
      inputs:
        base-branch:
          description: The branch as base branch for the depedence update checks
          required: false
          type: string
          default: main
        target-branch:
          description: The branch as target branch for the depedence update checks
          required: false
          type: string
          default: updated-depedences
        working-dir:
          description: The working directory for the depedence update checks
          type: string
          default: 17-custom-actions/my-react
        debug:
          type: boolean
          default: false

permissions:
    contents: write
    pull-requests: write
      
jobs:
    depedency-update:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
            - name: check for depedency updates
              uses: ./.github/workflows/actions/js-depedence-update
              with: 
                base-branch: ${{ inputs.base-branch }}
                head-branch: ${{ inputs.target-branch }}
                working-directory: ${{ inputs.working-dir }}
                gh-token: ${{ secrets.GITHUB_TOKEN }}
                debug: $${{ inputs.debug }}

               